### ISSUE TITLE
Feature: Faction Specific Vehicle Spawning

### ISSUE THREAD

**Issue by neronix17** [neronix17/-O21-Vehicle-Framework#13]
Adding directly to pawn list for a faction has undesirable side effects, they spawn with no fuel and potentially have problems with vehicles being in the pilot/gunner/passenger slots of other vehicles.

**Comment by NinjaSiren** [comment]
Yup they do spawn without fuel and still running. Occupants of the vehicle
may actually escape, though at random.

Usually, the vehicle has complete amount of people inside. 1 gunner 1
driver 1 passenger (replacement for either two.)

Over all it's ok it just looks weird.

I'm the current developer of Yes, Vehicles, Finally! [O21] Vehicle
Framework is a requirement for my mod to run.

Ludeon Forums: https://ludeon.com/forums/index.php?topic=48126.0

**Comment by NinjaSiren** [comment]
defModException, what reference files I'll use? Other than Rimworld, Verse,
Vehicle Framework, System, and Harmony.

**Comment by neronix17** [comment]
I'll be frank with you, the fact you're even asking that question shows I'd spend more time teaching you the basics than it'd take for me to just do it myself, which is what I'd prefer to do.

**Comment by NinjaSiren** [comment]
I can't yet do much C# coding yet, eh whatever it might be.

**Comment by neronix17** [comment]
After reviewing the code it seems there's ways in place already to set who can spawn in what roles on a vehicle.
