### ISSUE TITLE
Bug: No Way to Repair Vehicles

### ISSUE THREAD

**Issue by neronix17** [neronix17/-O21-Vehicle-Framework#2]
Repairing vehicles code is a bit fucked and resulted in pawns going to vehicles to fix them without any of the parts and obsessively working on them without ever actually repairing. So repairs were left out of the release.

**Comment by neronix17** [comment]
Vehicles can now be repaired, and will repair on a per part basis, so several burns and scratches will be repaired with a single operation if they were on a single "body part". They repair automatically, rather than using the surgery system, and can be assigned a specific item on a per-vehicle basis to repair with.

**Comment by TheEventHorizon** [comment]
Wait how was the bug fixed if the repository hasn't had any commits added to it since two weeks ago?

**Comment by NinjaSiren** [comment]
I guess fixed in his computer. But no commits yet.

**Comment by neronix17** [comment]
Yeah, it's not rocket science to figure out. I use issues as an issue tracker, like it's meant to be used, not for public notification of a bug being fixed.
