### ISSUE TITLE
Replace "Draft/Undraft" gizmo button with "Start/Stop Engine" text and graphics

### ISSUE THREAD

**Issue by sumghai** [neronix17/-O21-Vehicle-Framework#24]
(The following was originally posted in NinjaSiren/Yes-Vehicles-finally/issues/25)

At present, all vehicles still use the pawnlike "Draft/Undraft" gizmo button, which is a bit jarring considering that vehicles are more-or-less non-sentient unless there is a driver.

Would it be possible to override the current "Draft/Undraft" button with "Start/Stop Engine" text and graphics?

(For the record, I've made and customized gizmo buttons for my own Replimat mod, and overridden vanilla game methods, but I haven't tried to see if it is possible to also override gizmos)

**Comment by neronix17** [comment]
Not all of them have an engine. Leaving it as Draft/Undraft works for all vehicles not just for motorized ones.
