### ISSUE TITLE
Feature: Display max crew and passenger limits

### ISSUE THREAD

**Issue by sumghai** [neronix17/-O21-Vehicle-Framework#25]
At present, there is no intuitive way to tell the player in-game what the maximum number of occupants and/or passengers any given vehicle can take - players would have to keep loading colonists until the "Load Passenger" gizmo changes to "Unload Passenger", or otherwise have foreknowledge of the vehicle occupant capacity through examining the XML defs.

It would be nice if each vehicle's infobox displays the max crew and passenger limits - this could be done through a new StatWorker that pulls the number of `slots` per `role` defined in the vehicle's def.

e.g. Crew Occupancy: 6 (1 Driver, 1 Gunner, 4 Passengers)

**Comment by neronix17** [comment]
The whole framework is being rewritten from scratch to get rid of outdated methods and have things exactly like this done in a better way. The rebuilt version will have it all be in its own ITab to better display slots and their purpose, in a more useful manner. This'll also include the option to switch passenger seats to increase the storage capacity at the cost of a pawn slot for example.
